begin;
create extension if not exists pgtap;
set local role postgres;
select plan(28);

select has_table('public','assignment_batches','assignment batch table exists');
select has_table('public','assignment_batch_members','assignment batch members exist');
select has_table('public','work_tasks','role-aware to-do table exists');
select has_table('public','calendar_events','calendar events exist');
select has_table('public','notification_preferences','notification preferences exist');
select has_table('public','user_notifications','in-app notifications exist');
select has_table('public','notification_outbox','retryable delivery outbox exists');
select has_table('public','announcements','announcements exist');
select has_table('public','announcement_receipts','announcement receipts exist');
select has_table('public','operational_audit_events','immutable operational audit exists');
select has_column('public','learning_assignments','assignment_batch_id','assignment links to its batch');
select has_column('public','learning_assignments','manager_user_id','assignment records its manager');
select has_column('public','learning_assignments','priority','assignment records priority');
select has_function('public','create_assignment_batch',array['uuid','text','assignment_scope_kind','uuid[]','uuid','uuid','organization_role','uuid','uuid','assignment_priority','timestamp with time zone','timestamp with time zone','jsonb'],'batch assignment RPC exists');
select has_function('public','save_notification_preferences',array['uuid','notification_digest','boolean','boolean','boolean','boolean','boolean'],'preference RPC exists');
select has_function('public','mark_user_notification_read',array['uuid'],'notification read RPC exists');
select has_function('public','publish_announcement',array['uuid','text','text','announcement_scope_kind','uuid','uuid','organization_role','assignment_priority','timestamp with time zone'],'announcement RPC exists');
select has_function('public','refresh_operational_deadlines',array['uuid'],'deadline refresh RPC exists');
select has_function('public','claim_notification_outbox',array['integer'],'outbox claim RPC exists');
select has_function('public','finish_notification_delivery',array['uuid','boolean','text','text'],'outbox result RPC exists');
select ok(not has_function_privilege('anon','public.create_assignment_batch(uuid,text,assignment_scope_kind,uuid[],uuid,uuid,organization_role,uuid,uuid,assignment_priority,timestamptz,timestamptz,jsonb)','EXECUTE'),'anonymous assignment execution denied');
select ok(has_function_privilege('authenticated','public.create_assignment_batch(uuid,text,assignment_scope_kind,uuid[],uuid,uuid,organization_role,uuid,uuid,assignment_priority,timestamptz,timestamptz,jsonb)','EXECUTE'),'authenticated guarded assignment execution granted');
select ok(not has_function_privilege('authenticated','public.claim_notification_outbox(integer)','EXECUTE'),'browser users cannot claim email deliveries');
select ok(has_function_privilege('service_role','public.claim_notification_outbox(integer)','EXECUTE'),'service worker can claim email deliveries');
select is((select count(*)::int from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('assignment_batches','assignment_batch_members','work_tasks','calendar_events','notification_preferences','user_notifications','notification_outbox','announcements','announcement_receipts','operational_audit_events') and c.relrowsecurity and c.relforcerowsecurity),10,'all Phase 5 tables force RLS');
select is((select count(*)::int from pg_policies where schemaname='public' and tablename='notification_outbox'),0,'delivery outbox has no browser RLS policy');
select is((select state::text from public.skillward_feature_flags where feature_key='assignments_notifications_v2'),'Enabled','Phase 5 feature is enabled');
select matches((select obj_description('public.notification_outbox'::regclass)),'does not claim delivery','email delivery limitation is documented');

select * from finish();
rollback;
