const assert=require("node:assert/strict");
const fs=require("node:fs");
const test=require("node:test");
const app=fs.readFileSync("app.js","utf8"),db=fs.readFileSync("src/database-service.js","utf8"),css=fs.readFileSync("styles.css","utf8"),migration=fs.readFileSync("supabase/migrations/20260825020000_phase_5_assignment_operations.sql","utf8");

test("Phase 5 provides multi-level assignments with complete ownership metadata",()=>{
  for(const label of ["MULTI-LEVEL ASSIGNMENT","Selected Cohort","Role Group","Renewal interval days","ASSIGNMENTS · CALENDAR · TO-DO"]) assert.match(app,new RegExp(label,"i"));
  for(const field of ["created_by","starts_at","due_at","trainer_user_id","manager_user_id","priority","renewal_rule"]) assert.match(migration,new RegExp(field));
  assert.match(migration,/when 'Department'/);
  assert.match(migration,/when 'Facility'/);
  assert.match(migration,/when 'Role Group'/);
});

test("role-aware calendar and to-do stages are generated by the database",()=>{
  for(const table of ["assignment_batches","assignment_batch_members","work_tasks","calendar_events"]) assert.match(migration,new RegExp(`create table public\\.${table}`));
  for(const task of ["Complete Learning","Practical Observation","Worker Acknowledgement","Management Approval","Reassessment","Renewal"]) assert.match(migration,new RegExp(task));
  for(const event of ["Pathway Start","Pathway Due","Practical Assessment","Competency Expiry","Renewal"]) assert.match(migration,new RegExp(event));
  assert.match(migration,/create trigger sync_phase5_workflow/);
});

test("notifications use preferences and a retryable provider-confirmed outbox",()=>{
  for(const table of ["notification_preferences","user_notifications","notification_outbox"]) assert.match(migration,new RegExp(`create table public\\.${table}`));
  assert.match(migration,/for update skip locked/);
  assert.match(migration,/attempt_count>=5/);
  assert.match(migration,/does not claim delivery unless a configured provider worker records success/);
  assert.match(app,/Email delivery is never marked delivered until a configured provider confirms it/);
  assert.doesNotMatch(migration,/grant (select|insert|update|delete)[^;]*notification_outbox[^;]*to authenticated/i);
});

test("announcements and audit history stay organisation scoped and immutable",()=>{
  assert.match(migration,/create table public\.announcements/);
  assert.match(migration,/create table public\.announcement_receipts/);
  assert.match(migration,/create table public\.operational_audit_events/);
  assert.match(migration,/ordinary users have no mutation policy or table write grant/);
  assert.match(migration,/force row level security/);
  assert.match(migration,/private\.phase5_member/);
});

test("database service and navigation expose Phase 5 to every operational role",()=>{
  for(const method of ["createAssignmentBatch","saveNotificationPreferences","markUserNotificationRead","publishAnnouncement","markAnnouncementRead","refreshOperationalDeadlines"]) assert.match(db,new RegExp(method));
  assert.match(app,/\["work", "Work", "◫"\]/);
  assert.match(app,/function renderPhase5Operations/);
  assert.match(app,/notification-button[\s\S]+activeWorkspaceView = "work"/);
});

test("Phase 5 layout stacks safely for tablet and phone",()=>{
  assert.match(css,/@media\(max-width:900px\)\{\.phase5-form-grid/);
  assert.match(css,/@media\(max-width:560px\)\{\.phase5-form/);
  assert.match(css,/\.phase5-operations-grid/);
});
