const brand = `<a class="public-brand" href="/" aria-label="SkillWard home"><svg viewBox="0 0 48 54" aria-hidden="true"><path d="M24 2 44 9v16c0 13-8 22-20 28C12 47 4 38 4 25V9L24 2Z"/><path class="brand-check" d="m14.5 27.5 6.2 6.2 13-14"/></svg><span>SkillWard</span></a>`;
const header = `<a class="skip-link" href="#main-content">Skip to content</a><header class="public-header" data-public-header>${brand}<button class="menu-toggle" type="button" aria-expanded="false" aria-controls="public-navigation"><span></span><span></span><span></span><b>Menu</b></button><nav class="public-navigation" id="public-navigation" aria-label="Main navigation"><a href="/why-skillward/">Why SkillWard</a><a href="/platform/">Platform</a><a href="/solutions/hospitals/">Solutions</a><a href="/customers/">Customers</a><a href="/resources/">Resources</a><a href="/security/">Security</a><a class="nav-signin" href="/app/">Sign In</a><a class="button button-small" href="/book-demo/">Book a Demo</a></nav></header>`;
const footer = `<footer class="public-footer"><div class="section-shell footer-grid"><div>${brand}<p>Healthcare workforce learning, competency and compliance.</p></div><nav><strong>Platform</strong><a href="/platform/">Overview</a><a href="/why-skillward/">Why SkillWard</a><a href="/demo/">Guided Demo</a></nav><nav><strong>Organisation</strong><a href="/solutions/hospitals/">Hospitals</a><a href="/customers/">Customers</a><a href="/book-demo/">Book a Demo</a></nav><nav><strong>Trust &amp; Support</strong><a href="/security/">Security</a><a href="/legal/privacy/">Privacy</a><a href="/legal/terms/">Terms</a><a href="/contact/">Contact</a></nav></div><div class="section-shell footer-bottom"><span>© 2026 SkillWard. All rights reserved.</span><span>Training content does not replace workplace policies, clinical guidelines or professional judgement.</span></div></footer>`;
const cta = `<section class="final-cta"><div class="section-shell"><p class="public-eyebrow">READY FOR THE NEXT STEP?</p><h2>Build a workforce that is trained, assessed and ready.</h2><div class="button-row"><a class="button button-light" href="/book-demo/">Book a SkillWard Demo</a><a class="button button-outline-light" href="/book-demo/?interest=pilot">Discuss a Pilot</a></div></div></section>`;
const escapeJson = value => JSON.stringify(value).replace(/</g, "\\u003c");
export function pageShell({ title, description, path, body, noindex = false }) {
  const schema = { "@context":"https://schema.org", "@type":"SoftwareApplication", name:"SkillWard", applicationCategory:"BusinessApplication", operatingSystem:"Web", description:"Healthcare workforce learning, competency and compliance platform." };
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${description}"><meta name="theme-color" content="#0b3444">${noindex ? '<meta name="robots" content="noindex">' : ""}<meta property="og:type" content="website"><meta property="og:title" content="${title} | SkillWard"><meta property="og:description" content="${description}"><meta property="og:url" content="https://skillwardtraining.com${path}"><meta property="og:image" content="https://skillwardtraining.com/icon-512.png"><title>${title} | SkillWard</title><link rel="canonical" href="https://skillwardtraining.com${path}"><link rel="icon" href="/skillward-app-icon.svg"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/marketing.css?v=20260825-phase8-mobile-pwa-1"><script type="application/ld+json">${escapeJson(schema)}</script></head><body class="marketing-site">${header}<main id="main-content">${body}</main>${footer}<script src="/runtime-config.js"></script><script src="/pwa-controller.js?v=20260825-phase8-mobile-pwa-1" defer></script><script src="/marketing.js?v=20260825-phase8-mobile-pwa-1" defer></script></body></html>`;
}
const hero = (eyebrow, title, intro, status = "") => `<section class="content-hero"><div class="section-shell">${status ? `<span class="status-label">${status}</span>` : ""}<p class="public-eyebrow">${eyebrow}</p><h1>${title}</h1><p>${intro}</p></div></section>`;
const split = (title, copy, list, visualTitle = "Representative product workflow") => `<section class="content-section"><div class="section-shell content-grid"><div><h2>${title}</h2><p>${copy}</p><ul class="feature-list">${list.map(item => `<li>${item}</li>`).join("")}</ul></div><aside class="info-card"><p class="public-eyebrow">PRODUCT VIEW</p><h3>${visualTitle}</h3><div class="product-mock"><div><span></span>Assigned learning</div><div><span></span>Evidence and observations</div><div><span></span>Approval and renewal status</div></div><p>Representative interface only. Records shown are not patient or customer data.</p></aside></div></section>`;
const process = items => `<section class="content-section alt"><div class="section-shell content-grid"><div><p class="public-eyebrow">HOW IT WORKS</p><h2>An operational workflow, not a completion counter.</h2><p>Each action belongs to an authorised role and remains connected to the exact organisation, department, worker and pathway.</p></div><ol class="process-list">${items.map(item => `<li>${item}</li>`).join("")}</ol></div></section>`;

const capabilityData = {
  "learning": ["Learning & Pathway Management", "Assign structured, role-based learning without losing the local healthcare context.", "Managers and workers", ["Published pathway assignment", "Department and role scope", "Deadlines and progress", "Exact version retained with the training record"]],
  "knowledge-checks": ["Knowledge Checks", "Validate understanding before a worker moves into practical assessment.", "Workers, educators and managers", ["Multiple-choice knowledge validation", "Pass marks and attempts", "Results connected to assignments", "Content authoring enhancements are in development"]],
  "practical-assessment": ["Practical Competency Assessment", "Move beyond online completion with observed workplace capability.", "Trainers, workers and managers", ["Assigned trainer relationships", "Practical observations and comments", "Competent, needs development or not observed outcomes", "Evidence remains department-scoped"]],
  "trainer-recommendations": ["Trainer Recommendations", "Give trainers a controlled route to recommend competency or further development.", "Trainers and managers", ["Assigned trainees only", "Recommendation recorded against the assignment", "Approved content cannot be edited by trainers", "Management retains final approval"]],
  "management-approval": ["Management Approval", "Ensure competency is reviewed by authorised management before it becomes a record.", "Department and organisation managers", ["Pending sign-off visibility", "Evidence review", "Approve or request reassessment", "Decision retained in audit history"]],
  "renewal": ["Reassessment & Renewal Monitoring", "Keep future capability requirements visible after initial competency.", "Workers, trainers and managers", ["Renewal date visibility", "Expiry and reassessment status", "Reminder-ready data model", "Historical evidence retained"]],
  "pathway-builder": ["Healthcare Pathway Builder", "Guide organisations from a SkillWard template to reviewed local content.", "Educators and content administrators", ["Template-led setup", "Modules, lessons and objectives", "Clinical review and approval", "Version history and publishing"], true],
  "multi-organisation": ["Multi-organisation Administration", "Give each organisation a private workspace with separate facilities, departments, users and records.", "SkillWard and organisation administrators", ["Organisation workspace switching", "Facility and department structure", "Active membership required", "Row Level Security boundaries"]],
  "assignments": ["Staff & Trainer Assignment", "Make responsibility clear across workers, trainers, managers and departments.", "Organisation and department managers", ["Role-scoped invitations", "Facility and department access", "Trainer-to-trainee relationships", "Workers cannot change their own authority"]],
  "reporting": ["Reporting & Audit History", "Create a reliable record of who trained, assessed, recommended and approved.", "Managers and administrators", ["Department readiness views", "Training and competency status", "Immutable ordinary-user audit history", "Organisation-wide reporting continues to expand"]]
};
export const pages = [];
for (const [slug, [title, intro, roles, features, development]] of Object.entries(capabilityData)) {
  pages.push({ path:`platform/${slug}/index.html`, html:pageShell({ title, description:intro, path:`/platform/${slug}/`, body:`${hero("PLATFORM CAPABILITY", title, intro, development ? "IN DEVELOPMENT" : "CURRENT FOUNDATION")}${split("The customer problem", "Traditional course completion can leave practical capability, approval responsibility and reassessment disconnected. SkillWard keeps the operational evidence together.", features, title)}${process([`Authorised ${roles.toLowerCase()} open the role-appropriate workspace.`, "The action is restricted to the correct organisation, facility and department.", "Evidence remains connected to the training assignment and version.", "The next responsible role receives a clear decision point."])}${development ? '<section class="content-section"><div class="section-shell"><p class="notice">This capability is in development and is not represented as production-ready.</p></div></section>' : ""}${cta}` }) });
}

const capabilityLinks = Object.entries(capabilityData).map(([slug, value]) => `<a class="resource-card" href="/platform/${slug}/"><span>${value[4] ? "IN DEVELOPMENT" : "CAPABILITY"}</span><h3>${value[0]}</h3><p>${value[1]}</p></a>`).join("");
pages.push({path:"platform/index.html",html:pageShell({title:"Platform",description:"Explore SkillWard learning, practical competency, approval, renewal and administration capabilities.",path:"/platform/",body:`${hero("THE SKILLWARD PLATFORM","Learning connected to workplace competency.","SkillWard brings role-based learning, knowledge validation, observed assessment, management approval and reassessment into one accountable workflow.")}<section class="content-section"><div class="section-shell resource-grid">${capabilityLinks}</div></section>${process(["Organisation creates its secure workspace.","Administrators configure facilities, departments and roles.","Educators use an approved pathway or template.","Managers assign learning and deadlines.","Workers learn and validate understanding.","Trainers conduct practical assessments.","Managers approve competency.","SkillWard records evidence and monitors renewal."])}${cta}`})});
pages.push({path:"why-skillward/index.html",html:pageShell({title:"Why SkillWard",description:"Why healthcare organisations need competency evidence beyond course completion.",path:"/why-skillward/",body:`${hero("WHY SKILLWARD","Training completed isn’t the same as competency proven.","Healthcare workforce readiness depends on what a worker understands, what they can demonstrate and who has approved the evidence—not only whether a lesson was opened.")}${split("Completion can leave important questions unanswered","Can the worker perform the task? Was capability observed? Who reviewed the evidence? When must it be reassessed? SkillWard is designed to keep those answers connected.",["Learning assigned by role and department","Knowledge validation before practice","Observed workplace assessment","Management approval","Renewal and reassessment visibility"])}${cta}`})});

const hospitalBody = `${hero("HOSPITAL SOLUTION","Hospital workforce training that leads to competency evidence.","SkillWard’s initial active environment supports hospital department onboarding, PCA and Cleaner pathways, trainers, managers, practical assessment and reassessment.","INITIAL ACTIVE ENVIRONMENT")}${split("Start with one department and prove the workflow","Operating Theatre and Recovery is the current pathway example. Other hospital departments remain planned until their content is locally reviewed and approved.",["Private hospital workspace","Facilities and departments","PCA and Cleaner role pathways","Assigned trainers and managers","Practical observations and competency decisions"])}${process(["Configure the hospital facility and department.","Invite authorised managers, educators, trainers and workers.","Assign the approved Operating Theatre and Recovery pathway.","Complete learning and knowledge checks.","Observe practical capability and record evidence.","Approve competency and monitor reassessment."])}${cta}`;
pages.push({path:"solutions/hospitals/index.html",html:pageShell({title:"Hospitals",description:"Hospital department onboarding, workforce learning, practical competency and reassessment with SkillWard.",path:"/solutions/hospitals/",body:hospitalBody})});
for(const [slug,title,intro] of [["aged-care","Aged Care","Sample workforce onboarding, capability and compliance workflows for aged-care organisations."],["disability-support","Disability Support","Sample worker training, practical capability and continuing-development workflows for disability-support organisations."]]) pages.push({path:`solutions/${slug}/index.html`,html:pageShell({title,description:intro,path:`/solutions/${slug}/`,body:`${hero("INTERACTIVE SECTOR SAMPLE",title,intro,"GUIDED DEMO AVAILABLE")}<section class="content-section"><div class="section-shell legal-copy"><h2>Explore the complete SkillWard structure</h2><p>The Guided Demo includes a sample ${title} organisation, facility, departments, roles, pathway modules and the full Learn → Validate → Observe → Approve → Renew journey.</p><p class="notice">Demonstration content is sample-only and is not approved clinical or workplace instruction. Production use still requires organisation review and approval.</p><a class="button" href="/demo/">Open Guided Demo</a></div></section>${cta}`})});

pages.push({path:"customers/index.html",html:pageShell({title:"Customers",description:"SkillWard is built around frontline healthcare workforce challenges and is seeking authorised pilot partners.",path:"/customers/",body:`${hero("CUSTOMERS","Built around frontline healthcare experience.","SkillWard is being developed around real workforce onboarding, training and competency challenges. Customer evidence will only appear here with explicit authorisation.")}<section class="content-section"><div class="section-shell content-grid"><div><h2>Become a pilot partner</h2><p>Help test one secure, approved pathway with a small authorised workforce group and a clearly agreed evaluation plan.</p><ul class="feature-list"><li>No invented customer logos or endorsements</li><li>No patient data required for the intended workflow</li><li>Local content remains organisation-controlled</li><li>Results published only with authorisation</li></ul><a class="button" href="/book-demo/?interest=pilot">Discuss a Pilot</a></div><aside class="info-card"><p class="public-eyebrow">EVIDENCE FRAMEWORK</p><h3>Ready for verified proof</h3><p>The page structure is prepared for approved logos, case studies, testimonials, videos and measured pilot outcomes without needing a redesign.</p></aside></div></section>${cta}`})});
pages.push({path:"resources/index.html",html:pageShell({title:"Resources",description:"SkillWard healthcare onboarding, practical competency and pilot resources.",path:"/resources/",body:`${hero("RESOURCES","Practical guidance for workforce readiness.","A growing resource centre for organisations planning healthcare onboarding, practical assessment and competency assurance.")}<section class="content-section"><div class="section-shell resource-grid">${[["OVERVIEW","Healthcare onboarding guide","Questions to answer before assigning local training."],["OVERVIEW","Practical assessment guide","How roles and evidence fit together."],["CHECKLIST","Training compliance checklist","A starting structure for deadlines and reassessment."],["PILOT","Hospital pilot guide","How to scope one controlled pathway pilot."],["WALKTHROUGH","Product walkthroughs","Honest interface and workflow demonstrations."],["COMING LATER","Case studies & product updates","Reserved for authorised evidence and genuine news."]].map(x=>`<article class="resource-card"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join("")}</div></section>${cta}`})});

const trustItems=[["Multi-organisation separation","Organisation-owned records include an organisation boundary and are protected by active membership checks."],["Role-based access","Authorisation comes from protected memberships and assignments—not editable browser metadata."],["Department scope","Managers and trainers are limited to authorised facilities, departments and relationships."],["Authentication","Supabase authentication provides secure sessions, invitation and password-recovery foundations."],["Protected storage","Organisation-aware storage policies separate approved file paths."],["Audit history","Key administrative, training, assessment and support actions are designed to remain attributable."],["Backups and recovery","Operational backup and recovery procedures require final production configuration and regular testing."],["Incident readiness","A documented incident-response process and contact path are required before a hospital pilot."],["Privacy and minimisation","The intended training workflow does not require patient information; organisations should not upload it."]];
pages.push({path:"security/index.html",html:pageShell({title:"Security & Trust",description:"SkillWard security architecture, data separation, access control, privacy and readiness principles.",path:"/security/",body:`${hero("SECURITY & TRUST","Trust must be designed into every workforce decision.","SkillWard’s foundation uses multi-organisation separation, role-scoped access and auditable workflows. We make no claim of external certification that has not been formally achieved.")}<section class="content-section"><div class="section-shell trust-grid">${trustItems.map(x=>`<article class="trust-card"><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join("")}</div></section><section class="content-section alt"><div class="section-shell legal-copy"><h2>Current assurance position</h2><p>SkillWard is not claiming ISO 27001, SOC 2, HIPAA certification, Australian government certification or external clinical approval. Formal risk assessment, penetration testing, operational monitoring, incident exercises and legal review remain required before production hospital use.</p><h2>Security contact</h2><p>Report a suspected security issue through <a class="text-link" href="/contact/">Contact &amp; Support</a>. Do not include passwords, patient information or sensitive workforce records in the initial message.</p></div></section>${cta}`})});

const interests=["Hospital workforce training","PCA training","Cleaner training","Practical competency assessment","Compliance and reassessment","Multi-facility management","Aged Care interest","Disability Support interest","Pilot partnership","General enquiry"];
const demoForm=`<form class="demo-form" id="demo-request-form"><div class="form-grid-public"><label>Work email<input name="workEmail" type="email" autocomplete="email" required maxlength="254"></label><label>Full name<input name="fullName" autocomplete="name" required maxlength="120"></label><label>Organisation name<input name="organizationName" autocomplete="organization" required maxlength="160"></label><label>Organisation type<select name="organizationType" required><option value="">Choose type</option><option>Hospital</option><option>Aged Care</option><option>Disability Support</option><option>Other healthcare</option></select></label><label>Job role<input name="jobRole" required maxlength="120"></label><label>Number of staff<select name="staffRange" required><option value="">Choose range</option><option>1–49</option><option>50–199</option><option>200–999</option><option>1,000+</option></select></label><label class="full">Primary interest<select id="primary-interest" name="primaryInterest" required><option value="">Choose interest</option>${interests.map(x=>`<option value="${x}">${x}</option>`).join("")}</select></label><label class="full">Optional message<textarea name="message" maxlength="1500"></textarea></label><label class="honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><label class="full consent-row"><input name="privacyConsent" value="true" type="checkbox" required><span>I agree that SkillWard may use this business information to respond to my request. See the <a class="text-link" href="/legal/privacy/">Privacy Policy</a>.</span></label></div><button class="button" type="submit">Request a SkillWard Demo</button><p class="form-status" id="demo-form-status" aria-live="polite"></p></form>`;
pages.push({path:"book-demo/index.html",html:pageShell({title:"Book a Demo",description:"Request a tailored SkillWard demonstration or discuss a healthcare pilot.",path:"/book-demo/",body:`${hero("BOOK A DEMO","See SkillWard through your organisation’s workflow.","Every organisation’s workforce, departments and procedures are different. A SkillWard demonstration focuses on the roles, workflows and competency requirements that matter to your organisation.")}<section class="content-section"><div class="section-shell form-layout"><div><h2>What to expect</h2><ul class="feature-list"><li>A focused discussion about your workforce roles</li><li>A walkthrough of learning-to-competency workflow</li><li>Honest explanation of available and developing capabilities</li><li>Security, pilot and implementation questions</li></ul><p><a class="text-link" href="/security/">Review Security &amp; Trust →</a></p></div>${demoForm}</div></section>`})});
pages.push({path:"contact/index.html",html:pageShell({title:"Contact & Support",description:"Contact SkillWard for product, pilot, account or security support.",path:"/contact/",body:`${hero("CONTACT & SUPPORT","How can we help?","Choose the safest route for your enquiry. Never send passwords, patient information or confidential workforce evidence through a public message.")}<section class="content-section"><div class="section-shell resource-grid"><a class="resource-card" href="/book-demo/"><span>ORGANISATIONS</span><h3>Product and pilot enquiries</h3><p>Request a tailored demonstration or discuss a pilot.</p></a><a class="resource-card" href="/app/"><span>ACCOUNT</span><h3>Sign-in and recovery</h3><p>Use the secure application entry and password-recovery process.</p></a><a class="resource-card" href="/security/"><span>SECURITY</span><h3>Report a concern</h3><p>Review the security contact process before reporting an issue.</p></a></div></section>${cta}`})});

const legalPages={"privacy":["Privacy Policy","This draft explains SkillWard’s intended approach to business contact information, account data, workforce training records and privacy minimisation.",["SkillWard intends to collect only information needed to provide demonstrations, secure accounts and workforce learning services.","The intended training workflow does not require patient information. Organisations and users should not enter patient information into SkillWard.","Demo-request information is restricted to authorised SkillWard administrators and used to respond to the enquiry.","Production retention periods, overseas disclosures, subprocessors and Australian Privacy Act obligations require formal legal review."]],"terms":["Terms of Use","Draft conditions for access to SkillWard’s public website, Demo Mode and operational application.",["Demo Mode uses sample information and must not be treated as approved clinical instruction.","Organisations remain responsible for local procedure review, clinical approval and workforce decisions.","Users must not attempt to access another organisation, facility, department or person’s records.","Commercial terms, service levels, warranties and liability provisions require formal legal review before customer contracting."]],"accessibility":["Accessibility","SkillWard aims to provide an inclusive experience across public and operational screens.",["Semantic page structure and descriptive headings","Keyboard-operable navigation and controls","Visible focus indicators and readable contrast","Reduced-motion support and responsive layouts","An accessibility testing and feedback process remains ongoing"]]};
for(const [slug,[title,intro,items]] of Object.entries(legalPages)) pages.push({path:`legal/${slug}/index.html`,html:pageShell({title,description:intro,path:`/legal/${slug}/`,body:`${hero("LEGAL & SUPPORT",title,intro)}<section class="content-section"><div class="section-shell legal-copy"><p class="legal-review">Draft for Australian legal review. This content is not represented as lawyer-approved.</p>${items.map((item,index)=>`<h2>${index+1}. ${["Purpose and scope","Responsible use","Data and access","Review status","Accessibility commitment"][index]||"Our approach"}</h2><p>${item}</p>`).join("")}<h2>Questions</h2><p>Use <a class="text-link" href="/contact/">Contact &amp; Support</a> for questions about this page.</p></div></section>`})});

pages.push({path:"404.html",html:pageShell({title:"Page Not Found",description:"The requested SkillWard page could not be found.",path:"/404.html",noindex:true,body:`<section class="not-found"><strong>404</strong><h1>That page isn’t here.</h1><p>Return to the public website or open the secure application.</p><div class="button-row" style="justify-content:center"><a class="button" href="/">Return home</a><a class="button button-secondary" href="/app/">Sign In</a></div></section>`})});
