-- SkillWard application schema. It intentionally contains no patient/clinical records.
create extension if not exists pgcrypto;
create type public.workplace_role as enum ('Hospital Administrator','Department Manager','PCA','Cleaner','PCA Trainer','Cleaner Trainer');
create type public.account_status as enum ('Invited','Active','Suspended','Archived');
create type public.employment_status as enum ('New Starter','Active','On Leave','Transferred','Former Staff');
create type public.training_status as enum ('Not Started','In Progress','Ready for Trainer Review','Sent to Management','Approved','Reassessment Required');
create type public.notification_status as enum ('Unread','Read','Archived');

create table public.hospitals (id uuid primary key default gen_random_uuid(), name text not null check (length(trim(name)) between 1 and 200), is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.departments (id uuid primary key default gen_random_uuid(), hospital_id uuid not null references public.hospitals, code text not null check(code ~ '^[A-Za-z0-9_-]{1,30}$'), name text not null check(length(trim(name))>0), description text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(hospital_id,code), unique(id,hospital_id));
create table public.user_profiles (user_id uuid primary key references auth.users(id), full_name text not null check(length(trim(full_name))>0), employee_id text not null check(length(trim(employee_id))>0), email_display text check(email_display is null or email_display ~* '^[^@]+@[^@]+$'), account_status public.account_status not null default 'Invited', employment_status public.employment_status not null default 'New Starter', employment_start_date date, active_hospital_id uuid references public.hospitals, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz, unique(active_hospital_id,employee_id), check ((account_status='Archived')=(archived_at is not null)));
create table public.hospital_memberships (id uuid primary key default gen_random_uuid(), hospital_id uuid not null references public.hospitals, user_id uuid not null references public.user_profiles, role public.workplace_role not null, account_status public.account_status not null default 'Active', created_by uuid references public.user_profiles, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(id,hospital_id));
create unique index one_current_hospital_membership on public.hospital_memberships(hospital_id,user_id) where account_status in ('Invited','Active','Suspended');
create table public.department_memberships (id uuid primary key default gen_random_uuid(), hospital_id uuid not null, department_id uuid not null, user_id uuid not null references public.user_profiles, role public.workplace_role not null, is_active boolean not null default true, assigned_by uuid references public.user_profiles, assigned_at timestamptz not null default now(), ended_at timestamptz, foreign key(department_id,hospital_id) references public.departments(id,hospital_id), check((is_active and ended_at is null) or not is_active));
create unique index one_active_department_role on public.department_memberships(department_id,user_id,role) where is_active;
create table public.trainer_assignments (id uuid primary key default gen_random_uuid(), hospital_id uuid not null, department_id uuid not null, trainer_user_id uuid not null references public.user_profiles, trainee_user_id uuid not null references public.user_profiles, trainer_role public.workplace_role not null, trainee_role public.workplace_role not null, is_active boolean not null default true, assigned_by uuid references public.user_profiles, assigned_at timestamptz not null default now(), ended_at timestamptz, change_reason text, foreign key(department_id,hospital_id) references public.departments(id,hospital_id), check(trainer_user_id<>trainee_user_id), check((trainer_role='PCA Trainer' and trainee_role='PCA') or (trainer_role='Cleaner Trainer' and trainee_role='Cleaner')));
create unique index one_active_trainer_assignment on public.trainer_assignments(hospital_id,trainee_user_id) where is_active;
create table public.trainer_capacity (trainer_user_id uuid not null references public.user_profiles, hospital_id uuid not null references public.hospitals, maximum_active_trainees integer not null default 8 check(maximum_active_trainees between 1 and 100), updated_by uuid references public.user_profiles, updated_at timestamptz not null default now(), primary key(trainer_user_id,hospital_id));
create table public.training_pathways (id uuid primary key default gen_random_uuid(), hospital_id uuid references public.hospitals, department_id uuid references public.departments, intended_role public.workplace_role not null check(intended_role in ('PCA','Cleaner')), title text not null, description text, version integer not null default 1 check(version>0), is_published boolean not null default false, is_active boolean not null default true, created_by uuid references public.user_profiles, approved_by uuid references public.user_profiles, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(hospital_id,title,version));
create table public.training_modules (id uuid primary key default gen_random_uuid(), pathway_id uuid not null references public.training_pathways, title text not null, description text, display_order integer not null check(display_order>=0), module_type text not null check(length(trim(module_type))>0), is_required boolean not null default true, is_published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(pathway_id,display_order));
create table public.lessons (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.training_modules, title text not null, content jsonb, content_reference text, media_reference text, display_order integer not null check(display_order>=0), is_published boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(module_id,display_order));
create table public.knowledge_questions (id uuid primary key default gen_random_uuid(), module_id uuid not null references public.training_modules, lesson_id uuid references public.lessons, question_type text not null check(question_type in ('single_choice','multiple_choice','true_false')), question_content text not null, display_order integer not null check(display_order>=0), is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.knowledge_answer_options (id uuid primary key default gen_random_uuid(), question_id uuid not null references public.knowledge_questions on delete cascade, option_content text not null, display_order integer not null, is_correct boolean not null default false, created_at timestamptz not null default now(), unique(question_id,display_order));
create table public.training_assignments (id uuid primary key default gen_random_uuid(), hospital_id uuid not null, department_id uuid not null, user_id uuid not null references public.user_profiles, pathway_id uuid not null references public.training_pathways, assigned_by uuid references public.user_profiles, assigned_at timestamptz not null default now(), due_date date, status public.training_status not null default 'Not Started', progress_percentage numeric(5,2) not null default 0 check(progress_percentage between 0 and 100), trainer_review_status public.training_status not null default 'Not Started', management_approval_status public.training_status not null default 'Not Started', renewal_date date, completed_at timestamptz, updated_at timestamptz not null default now(), foreign key(department_id,hospital_id) references public.departments(id,hospital_id));
create unique index one_open_pathway_assignment on public.training_assignments(user_id,pathway_id) where status not in ('Approved','Reassessment Required');
create table public.module_progress (id uuid primary key default gen_random_uuid(), training_assignment_id uuid not null references public.training_assignments, module_id uuid not null references public.training_modules, status public.training_status not null default 'Not Started', progress_percentage numeric(5,2) not null default 0 check(progress_percentage between 0 and 100), started_at timestamptz, completed_at timestamptz, last_activity_at timestamptz not null default now(), unique(training_assignment_id,module_id));
create table public.knowledge_check_attempts (id uuid primary key default gen_random_uuid(), training_assignment_id uuid not null references public.training_assignments, module_id uuid references public.training_modules, question_id uuid references public.knowledge_questions, attempt_number integer not null check(attempt_number>0), score numeric(5,2) check(score between 0 and 100), passed boolean, started_at timestamptz not null default now(), submitted_at timestamptz, check(module_id is not null or question_id is not null), unique(training_assignment_id,module_id,attempt_number));
create table public.practical_observations (id uuid primary key default gen_random_uuid(), hospital_id uuid not null, department_id uuid not null, training_assignment_id uuid not null references public.training_assignments, trainer_id uuid not null references public.user_profiles, observation_text text not null, outcome text not null check(outcome in ('Competent','Needs Development','Not Observed')), observed_at timestamptz not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(department_id,hospital_id) references public.departments(id,hospital_id));
create table public.signoff_recommendations (id uuid primary key default gen_random_uuid(), training_assignment_id uuid not null references public.training_assignments, trainer_id uuid not null references public.user_profiles, recommendation_status public.training_status not null check(recommendation_status in ('Sent to Management','Approved','Reassessment Required')), recommendation_text text, submitted_at timestamptz not null default now(), management_reviewer_id uuid references public.user_profiles, management_decision public.training_status check(management_decision in ('Approved','Reassessment Required')), management_feedback text, decision_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.competency_records (id uuid primary key default gen_random_uuid(), hospital_id uuid not null, department_id uuid not null, user_id uuid not null references public.user_profiles, pathway_id uuid not null references public.training_pathways, pathway_version integer not null check(pathway_version>0), approval_status public.training_status not null, approved_by uuid references public.user_profiles, approved_at timestamptz, renewal_date date, reassessment_status public.training_status not null default 'Not Started', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), foreign key(department_id,hospital_id) references public.departments(id,hospital_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), hospital_id uuid not null references public.hospitals, recipient_user_id uuid not null references public.user_profiles, notification_type text not null, title text not null, message text not null, related_record_type text, related_record_id uuid, status public.notification_status not null default 'Unread', created_at timestamptz not null default now(), read_at timestamptz);
create table public.staff_invitations (id uuid primary key default gen_random_uuid(), hospital_id uuid not null references public.hospitals, email text not null check(email ~* '^[^@]+@[^@]+$'), intended_role public.workplace_role not null, intended_department_id uuid references public.departments, token_hash text check(token_hash is null or length(token_hash)>=32), auth_invitation_reference text, status public.account_status not null default 'Invited', invited_by uuid not null references public.user_profiles, expires_at timestamptz not null, accepted_at timestamptz, created_at timestamptz not null default now());
create table public.transfer_history (id uuid primary key default gen_random_uuid(), hospital_id uuid not null references public.hospitals, user_id uuid not null references public.user_profiles, previous_department_id uuid references public.departments, new_department_id uuid references public.departments, previous_trainer_id uuid references public.user_profiles, new_trainer_id uuid references public.user_profiles, transferred_by uuid not null references public.user_profiles, reason text not null, transferred_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), hospital_id uuid not null references public.hospitals, department_id uuid references public.departments, actor_user_id uuid references public.user_profiles, actor_role public.workplace_role, action_type text not null, affected_user_id uuid references public.user_profiles, record_type text not null, record_id uuid not null, previous_values jsonb, new_values jsonb, reason text, created_at timestamptz not null default now());

create index departments_hospital_idx on public.departments(hospital_id); create index hm_user_idx on public.hospital_memberships(user_id,hospital_id); create index dm_user_idx on public.department_memberships(user_id,department_id) where is_active; create index trainer_trainee_idx on public.trainer_assignments(trainer_user_id,trainee_user_id) where is_active; create index training_user_idx on public.training_assignments(user_id,hospital_id); create index audit_hospital_created_idx on public.audit_logs(hospital_id,created_at desc); create index competency_renewal_idx on public.competency_records(renewal_date) where reassessment_status <> 'Reassessment Required';
