-- Every application table is deny-by-default; policies below grant narrow authenticated access.
do $$ declare t text; begin foreach t in array array['hospitals','departments','user_profiles','hospital_memberships','department_memberships','trainer_assignments','trainer_capacity','training_pathways','training_modules','lessons','knowledge_questions','knowledge_answer_options','training_assignments','module_progress','knowledge_check_attempts','practical_observations','signoff_recommendations','competency_records','notifications','staff_invitations','transfer_history','audit_logs'] loop execute format('alter table public.%I enable row level security',t); execute format('alter table public.%I force row level security',t); end loop; end $$;

create policy hospital_read on public.hospitals for select to authenticated using(public.has_hospital_role(id));
create policy hospital_admin_update on public.hospitals for update to authenticated using(public.has_hospital_role(id,array['Hospital Administrator']::public.workplace_role[])) with check(public.has_hospital_role(id,array['Hospital Administrator']::public.workplace_role[]));
create policy department_read on public.departments for select to authenticated using(public.has_department_access(id));
create policy department_admin_all on public.departments for all to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[])) with check(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]));
create policy own_or_management_profiles on public.user_profiles for select to authenticated using(user_id=auth.uid() or (active_hospital_id is not null and public.has_hospital_role(active_hospital_id,array['Hospital Administrator']::public.workplace_role[])) or exists(select 1 from public.department_memberships target join public.department_memberships actor on actor.department_id=target.department_id and actor.user_id=auth.uid() and actor.role='Department Manager' and actor.is_active where target.user_id=user_profiles.user_id and target.is_active));
create policy membership_read on public.hospital_memberships for select to authenticated using(user_id=auth.uid() or public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]));
create policy membership_admin_write on public.hospital_memberships for all to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[])) with check(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]));
create policy department_membership_read on public.department_memberships for select to authenticated using(user_id=auth.uid() or public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[]));
create policy department_membership_management on public.department_memberships for all to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[])) with check((public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[])) or (role<>'Hospital Administrator' and public.has_department_access(department_id,array['Department Manager']::public.workplace_role[])));
create policy trainer_assignment_read on public.trainer_assignments for select to authenticated using(trainee_user_id=auth.uid() or trainer_user_id=auth.uid() or public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[]));
create policy trainer_assignment_management on public.trainer_assignments for all to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[])) with check(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[]));
create policy capacity_read on public.trainer_capacity for select to authenticated using(trainer_user_id=auth.uid() or public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]));
create policy capacity_admin on public.trainer_capacity for all to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[])) with check(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]));
create policy pathway_assigned_read on public.training_pathways for select to authenticated using((is_published and (hospital_id is null or public.has_hospital_role(hospital_id))) or public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]));
create policy content_management on public.training_pathways for all to authenticated using(hospital_id is not null and public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[])) with check(hospital_id is not null and public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]));
create policy module_read on public.training_modules for select to authenticated using(is_published and exists(select 1 from public.training_pathways p where p.id=pathway_id and (p.hospital_id is null or public.has_hospital_role(p.hospital_id))));
create policy lesson_read on public.lessons for select to authenticated using(is_published and exists(select 1 from public.training_modules m join public.training_pathways p on p.id=m.pathway_id where m.id=module_id and (p.hospital_id is null or public.has_hospital_role(p.hospital_id))));
create policy question_read on public.knowledge_questions for select to authenticated using(is_active and exists(select 1 from public.training_modules m join public.training_pathways p on p.id=m.pathway_id where m.id=module_id and (p.hospital_id is null or public.has_hospital_role(p.hospital_id))));
-- No authenticated SELECT policy on answer options: correct answers remain server-only.
create policy assignment_read on public.training_assignments for select to authenticated using(user_id=auth.uid() or public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[]) or exists(select 1 from public.trainer_assignments x where x.trainer_user_id=auth.uid() and x.trainee_user_id=training_assignments.user_id and x.department_id=training_assignments.department_id and x.is_active));
create policy own_progress_read on public.module_progress for select to authenticated using(exists(select 1 from public.training_assignments a where a.id=training_assignment_id));
create policy own_progress_write on public.module_progress for all to authenticated using(exists(select 1 from public.training_assignments a where a.id=training_assignment_id and a.user_id=auth.uid())) with check(exists(select 1 from public.training_assignments a where a.id=training_assignment_id and a.user_id=auth.uid()));
create policy own_attempts on public.knowledge_check_attempts for all to authenticated using(exists(select 1 from public.training_assignments a where a.id=training_assignment_id and a.user_id=auth.uid())) with check(exists(select 1 from public.training_assignments a where a.id=training_assignment_id and a.user_id=auth.uid()));
create policy observation_authorized_read on public.practical_observations for select to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[]) or (trainer_id=auth.uid() and exists(select 1 from public.trainer_assignments x join public.training_assignments a on a.id=training_assignment_id where x.trainer_user_id=auth.uid() and x.trainee_user_id=a.user_id and x.department_id=practical_observations.department_id and x.is_active)));
create policy observation_trainer_insert on public.practical_observations for insert to authenticated with check(trainer_id=auth.uid() and exists(select 1 from public.trainer_assignments x join public.training_assignments a on a.id=training_assignment_id where x.trainer_user_id=auth.uid() and x.trainee_user_id=a.user_id and x.department_id=practical_observations.department_id and x.is_active));
create policy recommendation_read on public.signoff_recommendations for select to authenticated using(trainer_id=auth.uid() or exists(select 1 from public.training_assignments a where a.id=training_assignment_id and (a.user_id=auth.uid() or public.has_hospital_role(a.hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(a.department_id,array['Department Manager']::public.workplace_role[]))));
create policy recommendation_trainer_insert on public.signoff_recommendations for insert to authenticated with check(trainer_id=auth.uid() and management_decision is null and exists(select 1 from public.training_assignments a join public.trainer_assignments x on x.trainee_user_id=a.user_id where a.id=training_assignment_id and x.trainer_user_id=auth.uid() and x.is_active));
create policy recommendation_management_update on public.signoff_recommendations for update to authenticated using(exists(select 1 from public.training_assignments a where a.id=training_assignment_id and (public.has_hospital_role(a.hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(a.department_id,array['Department Manager']::public.workplace_role[])))) with check(management_reviewer_id=auth.uid());
create policy competency_management_read on public.competency_records for select to authenticated using(user_id=auth.uid() or public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[]));
create policy competency_management_write on public.competency_records for all to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[])) with check((approved_by=auth.uid() or approved_by is null) and (public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or public.has_department_access(department_id,array['Department Manager']::public.workplace_role[])));
create policy own_notifications on public.notifications for select to authenticated using(recipient_user_id=auth.uid()); create policy own_notification_update on public.notifications for update to authenticated using(recipient_user_id=auth.uid()) with check(recipient_user_id=auth.uid());
create policy invitations_admin on public.staff_invitations for all to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[])) with check(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) and (intended_role<>'Hospital Administrator' or public.current_hospital_role(hospital_id)='Hospital Administrator'));
create policy transfer_management_read on public.transfer_history for select to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or ((previous_department_id is not null and public.has_department_access(previous_department_id,array['Department Manager']::public.workplace_role[])) or (new_department_id is not null and public.has_department_access(new_department_id,array['Department Manager']::public.workplace_role[]))));
create policy audit_management_read on public.audit_logs for select to authenticated using(public.has_hospital_role(hospital_id,array['Hospital Administrator']::public.workplace_role[]) or (department_id is not null and public.has_department_access(department_id,array['Department Manager']::public.workplace_role[])));
-- No client INSERT/UPDATE/DELETE policies exist for audit logs.
